version: '3.3'

services:
    api:
        build: ./docker/node
        container_name: defenit-profile
        volumes:
            - ./data/node:/app
        environment:
            - NODE_ENV=development
        working_dir: /app
        ports:
            - '8080:8080'
        networks:
            defenit-profile:
                ipv4_address: 172.10.0.3

networks:
    defenit-profile:
        driver: bridge
        ipam:
            config:
                - subnet: 172.10.0.0/24
